[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = ".env"
solc_version = "0.8.19"
[dependencies]
openzeppelin-contracts = { version = "4.9.3" }



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
